### ISSUE TITLE
panic: Segmentation fault -- stopping myself...

### ISSUE THREAD

**Issue by Carol-Symbiomics** [pirovc/fgap#6]
Hi! I'm trying to use Fgap to gap filled a 10X linked reads assembled genome using supernova with the contigs generated by a DiscovarDenovo assembly.

I've run Fgap but after reading the dataset and prompting the message `Building database ...`
I get an error after which the run crashes

this is entire message
`panic: Segmentation fault -- stopping myself...
attempting to save variables to 'octave-workspace'...
save to 'octave-workspace' complete
/home/buitracn/.conda/envs/fgap/bin/FGAP: line 2: 29561 Segmentation fault      (core dumped) octave --path "/home/buitracn/.conda/envs/fgap/bin/" --no-gui --eval "fgap $@"`

How can I solve this problem. Any help will be greatly appreciated!

**Comment by pirovc** [comment]
Hi @Carol-Symbiomics 

Did you try to run FGAP with the sample data? Did it work? Which version of octave are you using?

Cheers
Vitor

**Comment by Carol-Symbiomics** [comment]
Hi @pirovc 

Thanks for your prompt reply. 
The octave version I have is 4.2.1.
FGAP runs well when I use the sample data  :(. Do you have any idea what might be the cause of the error I'm getting. Since the sample data runs well, I'm unsure how to address this issue

**Comment by pirovc** [comment]
Difficult to say, the error is very generic. Since your installation is working fine with the sample data, I think that one of the following reasons can be causing the crash:

- Your data can contain unexpected format/characters.
- The files are too big to be handled by octave/blast or you do not have enough memory

You can try to use just parts of your data (first 100 contigs, for example) to see if it works. 
Another alternative is to run FGAP with MCR (matlab compiler runtime, more info on README) which is more stable and faster than octave.
